### ISSUE TITLE
XCOM doesn't understand scientific notation

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#176]
If one provides mixtures with scientific notation for the fractional content, xcom seems to not be processing it correctly and becquerel throws an error:

```
bq.tools.fetch_xcom_data(['N 7.8e-1', 'O2 2.2e-1'], e_range_kev=[1, 10000])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/Work/Software/becquerel/becquerel/tools/xcom.py", line 450, in fetch_xcom_data
    query = _XCOMQuery(arg, **kwargs)
  File "/home/marco/Work/Software/becquerel/becquerel/tools/xcom.py", line 175, in __init__
    self.perform()
  File "/home/marco/Work/Software/becquerel/becquerel/tools/xcom.py", line 413, in perform
    self._parse_text()
  File "/home/marco/Work/Software/becquerel/becquerel/tools/xcom.py", line 379, in _parse_text
    tables = pd.read_html(self._text, header=0, skiprows=[1, 2])
  File "/usr/lib64/python3.6/site-packages/pandas/io/html.py", line 906, in read_html
    keep_default_na=keep_default_na)
  File "/usr/lib64/python3.6/site-packages/pandas/io/html.py", line 743, in _parse
    raise_with_traceback(retained)
  File "/usr/lib64/python3.6/site-packages/pandas/compat/__init__.py", line 344, in raise_with_traceback
    raise exc.with_traceback(traceback)
ValueError: No tables found
```
I don't think it is worth fixing this, or even our job, but I put this here for further reference

**Comment by cosama** [comment]
Just thought about this, and I honestly think it would be better to provide a dictionary with `"element": fraction` pairs instead of a table and then parse it internally into strings. Could we add that as an alternative for lists, and then maybe deprecated lists in the future?

**Comment by markbandstra** [comment]
That mixture fails to work when entered into the [mixtures web query](https://physics.nist.gov/cgi-bin/Xcom/xcom2), resulting in a returned page that says `Invalid Formulae`. Not parsing scientific notation correctly is an XCOM issue that becquerel does not catch. Right now becquerel only checks that each string in the list contains two items separated by a space, and that the second item parses to a `float` in python. It then joins the strings and sends them to the web query.

I agree with the request for dictionary support.

I propose the following:
* formatting the numbers into decimal when creating the query string
* adding support for dictionaries
* supporting the current list-of-strings format for a while but phasing it out
